name: "Production Server"
host: "0.0.0.0"
port: 8080
workers: 4
debug: false
log_level: "WARNING"

allowed_hosts:
  - "example.com"
  - "www.example.com"
  - "api.example.com"

middleware_config:
  cors:
    enabled: true
    origins: ["*"]
    methods: ["GET", "POST", "PUT", "DELETE"]
  auth:
    enabled: true
    type: "jwt"
    secret_key: "your-secret-key"
  rate_limiting:
    enabled: true
    requests_per_minute: 100
