name: Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,all]"

    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check

    - name: Check for outdated dependencies
      run: |
        pip list --outdated

    - name: Test with latest dependencies
      run: |
        pip install --upgrade --upgrade-strategy eager -e ".[dev,all]"
        pytest tests/ -v
