name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'
      - 'dataclass_cli/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,all]"

    - name: Generate API documentation
      run: |
        # Generate docstring-based API docs if needed
        python -c "
        import dataclass_cli
        import inspect

        # Simple API documentation generation
        print('# API Documentation\\n')

        # Document main functions
        for name in dir(dataclass_cli):
            if not name.startswith('_'):
                obj = getattr(dataclass_cli, name)
                if callable(obj) and hasattr(obj, '__doc__') and obj.__doc__:
                    print(f'## {name}\\n')
                    print(obj.__doc__.strip())
                    print()
        " > docs/API.md

    - name: Validate examples
      run: |
        cd examples
        python -m py_compile *.py
        echo "All examples compile successfully"

    - name: Test documentation examples
      run: |
        # Test that README examples work
        python -c "
        # Test basic example from README
        from dataclasses import dataclass
        from dataclass_cli import build_config_from_cli

        @dataclass
        class Config:
            name: str
            count: int = 10
            debug: bool = False

        config = build_config_from_cli(Config, ['--name', 'test'])
        assert config.name == 'test'
        print('README examples work correctly')
        "
