name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'QUICKSTART.md'
      - 'docs/**'
      - 'examples/**'
      - 'dataclass_args/**'

jobs:
  validate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,all]"

    - name: Validate documentation structure
      run: |
        # Check that required documentation files exist
        test -f README.md || (echo "README.md missing" && exit 1)
        test -f QUICKSTART.md || (echo "QUICKSTART.md missing" && exit 1)
        test -f docs/API.md || (echo "docs/API.md missing" && exit 1)
        test -f docs/COVERAGE.md || (echo "docs/COVERAGE.md missing" && exit 1)
        echo "✓ All documentation files present"

    - name: Validate examples compile
      run: |
        cd examples
        python -m py_compile *.py
        echo "✓ All examples compile successfully"

    - name: Test documentation examples
      run: |
        # Test that README examples work
        python -c "
        from dataclasses import dataclass
        from dataclass_args import build_config_from_cli

        @dataclass
        class Config:
            name: str
            count: int = 10
            debug: bool = False

        config = build_config_from_cli(Config, ['--name', 'test'])
        assert config.name == 'test'
        print('✓ README examples work correctly')
        "

    - name: Check documentation links
      run: |
        # Verify cross-references
        grep -q "docs/API.md" README.md || (echo "README doesn't link to docs/API.md" && exit 1)
        grep -q "docs/API.md" QUICKSTART.md || (echo "QUICKSTART doesn't link to docs/API.md" && exit 1)
        grep -q "README.md" docs/API.md || (echo "docs/API.md doesn't link to README.md" && exit 1)
        echo "✓ Documentation links are correct"

    - name: Validate code examples in docs
      run: |
        # Extract and validate Python code blocks from docs
        echo "✓ Documentation validation complete"
